#!/bin/bash

set -e

TMP=$(mktemp)

# Generate the txt-version from the staged xml
git show :draft-pfeifer-rtgwg-dmpr/draft-pfeifer-rtgwg-dmpr-00.xml > $TMP
xml2rfc $TMP -o draft-pfeifer-rtgwg-dmpr/draft-pfeifer-rtgwg-dmpr-00.txt
rm $TMP

git add draft-pfeifer-rtgwg-dmpr/draft-pfeifer-rtgwg-dmpr-00.txt
